---
abstract: 'Plugin that adds pure Perl config file support to CGI::Application'
author:
  - 'Mark Stosberg <mark@summersault.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Application-Plugin-Config-Perl
provides:
  CGI::Application::Plugin::Config::Perl:
    file: lib/CGI/Application/Plugin/Config/Perl.pm
    version: 1.50
requires:
  CGI::Application: 0
  Carp: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.50
